### PR TITLE
FIX: #46 | Code optimized and style fix

### PR DESCRIPTION
**Pull request by nishalbarman**
**Title:-**
On the home page we can see on one card the text is not completely visible, it goes under the bottom button. I can fix this issue.

**I moved some functions from Cards.jsx to App.jsx also I made it more readable and clean ...**

The **text-ellipsis** that has been achieved with javascript code can be achieved with normal CSS code or with tailwind also so I implemented that..

**Screenshots of before:-** 

_Card description :->_

Screenshot (90)

_Code  :->_ 

Screenshot (91)

**NOTE-> I have not attached the refactored code for this issue in the screenshot, because there is only a small change. _(I have just removed this js code and modified the CSS for the text)_**

**After the refactor:->**

_Card:->_

Screenshot (93)

_Code->_

Screenshot (94)

**NOTE :-> I have written all the codes for the filter in one function(**fetchData**) and in the App.jsx file only**

### CODE REVIEW

**Comment by nishalbarman** [comment]
Hello Admin, 
 
 A small request from my side, If you merge this PR please attach the hacktoberfest label. 
 I am okay with any changes required. 
 
Thank You.

**Comment by Zyro231-2** [comment]
Hey @nishalbarman please resolve conflicts

**Comment by nishalbarman** [comment]
I  got some other style issues, let me fix those also. The text that got changed to copied from the copy description has a color issue. When we release the hover the color also has white color so it is getting mixed with the background.

**Comment by nishalbarman** [comment]
Hey, @Zyro231-2  it's done! Can you check?

**Comment by Zyro231-2** [comment]
@nishalbarman Thank you for your contribution.

**Review by Zyro231-2 — APPROVED** [review]

**Pull request merged**
