### PR TITLE
Made the navbar with different categories sticky which allows users to effortlessly access and switch between various categories without the need to repeatedly scroll back to the top of the page. 

### PR DESCRIPTION
**Pull request by kharedevansh11**

### CODE REVIEW

**Comment by kharedevansh11** [comment]
Screenshot (14)
Now the user doesn't have to scroll back to the top to select a different option.

**Comment by Zyro231-2** [comment]
@kharedevansh11  what have you done you pushed node modules also

**Comment by kharedevansh11** [comment]
> @kharedevansh11 what have you done

I made the navbar with options of development,design etc. sticky. So the user doesn't have to scroll back up if they want to select a different option.

**Comment by Zyro231-2** [comment]
You didn't clone this repository.

**Comment by kharedevansh11** [comment]
I was having some issues in running it on my localhost so I did that. Shall I clone it again and then commit changes and raise a new PR? I am new to open source,so please can you guide me sir.

**Comment by Zyro231-2** [comment]
Read the README.md file first : https://github.com/Zyro231-2/Human_mg#getting-started

**Comment by kharedevansh11** [comment]
> Read the README.md file first : https://github.com/Zyro231-2/Human_mg#getting-started

Really sorry for the mess up I made previously. Please review my new PR.

**Pull request closed without merging**
