### PR TITLE
Fixed the responsiveness

### PR DESCRIPTION
**Pull request by barkhayadav12**

### CODE REVIEW

**Comment by barkhayadav12** [comment]
I was assigned to fix the responsiveness of the website but the website was already responsive, only the navbar wasn't responsive, so I have fixed that.
Before:
before
After:
after
Please check!

**Comment by Zyro231-2** [comment]
I can't merge all checks are failed.

**Comment by barkhayadav12** [comment]
How do i fix this?

**Comment by Zyro231-2** [comment]
Read https://github.com/Zyro231-2/Human_mg#getting-started

**Pull request closed without merging**
